### ISSUE TITLE
Missing phase information e. DRC 

### ISSUE THREAD

**Issue by ColeCampton** [TSSlade/unesco_equity#12]
There is no phase information for dataset e. DRC
(PUF_3.DRC2015-4Regions_grade3-5_EGRA-EGMA-SSME_French-Lingala-Tshiluba-Kiswahili)

Each entry lists year as 2015 as well.

**Comment by TSSlade** [comment]
Yes, that particular DRC dataset was a one-off. (Conducted to serve as a baseline for a program whose design was then delayed, and which once finalized bore little resemblance to the design for which that EGRA study was first developed.) There would be no phase data for that one.

If you want phased data for DRC (which you may only want if looking at these results in isolation suggest there is good enough performance to investigate further despite the severe skew in the performance distribution), look at the following files:
![image](https://user-images.githubusercontent.com/3211478/85460316-f37c1900-b557-11ea-9c52-7ce0b9ea00b3.png)
